import tkinter as tk
import random
'''
import subprocess
import sys

def import_or_install(module_name):
    try:
        __import__(module_name)
        pass
    except ImportError:
        print(f"The module '{module_name}' is not installed. Installing now...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", module_name])
        print(f"'{module_name}' has been installed successfully.")
'''

import io
import requests
from PIL import Image, ImageTk
import mysql.connector as sql

d = sql.connect(host='localhost', user='root', password='family123')
cr = d.cursor()

def display_info(info):
    text_box.delete('1.0', 'end')  
    text_box.insert('end', info)
    text_box.tag_configure("center", justify='center')
    text_box.tag_add("center", "1.0", "end")  


def facts():
    facts_list = [
        "N cannot share more than 3 e-, otherwise it will gain + charge",
        "The first member of each group show different behaviour - anomalous behaviour!",
        "H is abundantly present in the universe",
        "Pnictogens comes from a greek word,\'pnicoto\', which means \'to choke\'.",
        "Neon is mainly found in stars. Neon is the 5th most common element in the universe but comprises only 0.0018%\ of the Earth's atmosphere",
        "Technetium was the first element to be made artificially. It is the lightest element that has only radioactive isotopes (none are stable).",
        "Nature\'s Chosen One loves colors. Solid and liquid oxygen usually appear light blue, but it can also appear in red, orange, pink, and black!",
        "There are different forms of pure elements, called allotropes. Examples of allotropes of carbon include diamond, graphite, buckminsterfullerene, and amorphous carbon. Although they all consists of carbon atoms, these allotropes have different properties from each other.",
        "Chemical bonding is the glue that holds everything together, from the air we breathe to the water we drink. It determines the properties of substances and shapes the world around us.",
        "MARS is red due the presence of Iron oxide.",
        "\"J\" is the only letter which is not found in the periodic table.",
        "Dmitri Mendeleyev is the inventor of the modern periodic table",
        "Almost 75 percent of the periodic table is composed of metals.",
        "There are the elements named with the Greek word that best describes its properties. Argon is taken from the Greek word \'Argos,\' meaning \'lazy\' or \'idle.\' Bromine, which produces a horrible smell, is accurately named after the Greek word \'bromos,\' meaning \'stench.\'",
        "The physicist Richard Feynman predicted that, if it exists, we will never be able to observe the 137th element. That\'s partly because, theoretically, element 137\'s electrons would orbit at the speed of light. Hypothetically speaking, element 139\'s electrons would orbit faster than the speed of light, making it impossible given today\'s scientific knowledge."
    ]
    random_fact = random.choice(facts_list)
    display_info(random_fact)

cr.execute("SHOW DATABASES LIKE 'periodic_table'")
result = cr.fetchone()
if not result:
    cr.execute('create database periodic_table')
    cr.execute('use periodic_table')
    cr.execute('create table info(Name varchar(25), atm_no int primary key, atm_mass float ,block varchar(10), category varchar(30), configuration varchar(50), uses varchar(1000),url varchar(1000))')
    cr.execute('insert into info values(\'Hydrogen\', 1, 1.0078, \'s-block\', \'Alkali metal\', \'1s1\', \'Large quantities of H2 are used in the "upgrading" of fossil fuels. Key consumers of H2 include hydrodesulfurization, and hydrocracking. \',\'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Hydrogen_discharge_tube.jpg/450px-Hydrogen_discharge_tube.jpg\')')
    cr.execute('insert into info values(\'Helium\', 2, 4.0026, \'p-block\', \'Noble gas\', \'1s2\', \'Helium is used as a protective gas in growing silicon and germanium crystals, in titanium and zirconium production, and in gas chromatography, because it is inert\',\'https://www.alphabetu.com/-/media/Products/au/events/general-decorations/kg43he15-disposable-helium-tank-000.ashx?bc=FFFFFF&w=540&h=540\')')
    cr.execute('insert into info values(\'Lithium\', 3, 6.941, \'s-block\', \'Alkali metal\', \'[He] 2s1\', \'In 2021, most lithium is used to make lithium-ion batteries for electric cars and mobile devices.\',\'https://upload.wikimedia.org/wikipedia/commons/e/ed/Lithiumcut_cropped.jpg\')')
    cr.execute('insert into info values(\'Beryllium\', 4, 9.0122, \'s-block\', \'Alkaline earth metal\', \'[He] 2s2\',\'Because of its low atomic number and very low absorption for X-rays, the oldest and still one of the most important applications of beryllium is in radiation windows for X-ray tubes.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFDo9YIDLFgKRQIfK72ZuRm1upZMOrSEegBw&s\')')
    cr.execute('insert into info values(\'Boron\', 5, 10.811, \'p-block\', \'Icosagen\', \'[He] 2s2 2p1\', \'Boron is a useful dopant for such semiconductors as silicon, germanium, and silicon carbide.\',\'https://www.newtondesk.com/wp-content/uploads/2019/08/%CE%B2-rhombohedral-boron.png\')')
    cr.execute('insert into info values(\'Carbon\', 6, 12.011, \'p-block\', \'Tetrels\', \'[He] 2s2 2p2\', \'Plastics are made from synthetic carbon polymers, often with oxygen and nitrogen atoms included at regular intervals in the main polymer chain.\',\'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Glassy_carbon_and_a_1cm3_graphite_cube_HP68-79.jpg/330px-Glassy_carbon_and_a_1cm3_graphite_cube_HP68-79.jpg\')')
    cr.execute('insert into info values(\'Nitrogen\', 7, 14.007, \'p-block\', \'Pnictogen\', \'[He] 2s2 2p3\', \'Like dry ice, the main use of liquid nitrogen is for cooling to low temperatures. It is used in the cryopreservation of biological materials such as blood and reproductive cells (sperm and eggs).\',\'https://5.imimg.com/data5/CJ/OX/AG/SELLER-9472502/liquid-nitrogen-500x500.jpg\')')
    cr.execute('insert into info values(\'Oxygen\', 8, 15.999, \'p-block\', \'Chalcogen\', \'[He] 2s2 2p4\', \'Uptake of O2 from the air is the essential purpose of respiration, so oxygen supplementation is used in medicine.\',\'https://qph.cf2.quoracdn.net/main-qimg-8fd4230c88e25f244863634d7538bf87-lq\')')
    cr.execute('insert into info values(\'Fluorine\', 9, 18.998, \'p-block\', \'Halogen\', \'[He] 2s2 2p5\', \'Fluorosurfactants are small organofluorine molecules used for repelling water and stains\',\'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Fluoro_liquido_a_-196%C2%B0C_1.jpg/330px-Fluoro_liquido_a_-196%C2%B0C_1.jpg\')')
    cr.execute('insert into info values(\'Neon\', 10, 20.18, \'p-block\', \'Noble gas\', \'[He] 2s2 2p6\', \' Neon glow lamps are generally tiny, with most operating between 100 and 250 volts.\',\'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Neon_discharge_tube.jpg/330px-Neon_discharge_tube.jpg\')')
    cr.execute('insert into info values(\'Sodium\', 11, 22.99, \'s-block\', \'Alkali metal\', \'[Ne] 3s1\', \'In humans, sodium is an essential mineral that regulates blood volume, blood pressure, osmotic equilibrium and pH.\',\'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Na_%28Sodium%29.jpg/330px-Na_%28Sodium%29.jpg\')')
    cr.execute('insert into info values(\'Magnesium\', 12, 24.305, \'s-block\', \'Alkaline earth metal\', \'[Ne] 3s2\', \'The important interaction between phosphate and magnesium ions makes magnesium essential to the basic nucleic acid chemistry of all cells of all known living organisms\',\'https://5.imimg.com/data5/XX/GI/MY-29082668/laboratory-magnesium-ribbon.jpg\')')
    cr.execute('insert into info values(\'Aluminium\', 13, 26.982, \'p-block\', \'Icosagen\', \'[Ne] 3s2 3p1\', \'Commonly used in packaging, construction, and transportation.\', \'https://d1whtlypfis84e.cloudfront.net/guides/wp-content/uploads/2020/01/15143253/600px-Aluminium.jpg\')')
    cr.execute('insert into info values(\'Silicon\', 14, 28.086, \'p-block\', \'Tetrels\', \'[Ne] 3s2 3p2\', \'Essential for making semiconductors and solar cells.\', \'https://cdn1.byjus.com/wp-content/uploads/2017/10/Silicon-2.jpg\')')
    cr.execute('insert into info values(\'Phosphorous\', 15, 30.974, \'p-block\', \'Pnictogen\', \'[Ne] 3s2 3p3\', \'Used in fertilizers, detergents, and safety matches.\', \'https://5.imimg.com/data5/QH/OC/MY-34188929/red-phosphorous-500x500.jpg\')')
    cr.execute('insert into info values(\'Sulfur\', 16, 32.065, \'p-block\', \'Chalcogen\', \'[Ne] 3s2 3p4\', \'Used in vulcanization of rubber and in sulfuric acid production.\', \'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLn2U23x04H1vZOMTMPWGVWgfSlfEvLR8ghQ&s\')')
    cr.execute('insert into info values(\'Chlorine\', 17, 35.453, \'p-block\', \'Halogen\', \'[Ne] 3s2 3p5\', \'Disinfectant in water treatment and used in PVC production.\', \'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfddctpd4EuaxlnOzgxdd58sSrEckyD3mGSw&s\')')
    cr.execute('insert into info values(\'Argon\', 18, 39.948, \'p-block\', \'Noble gas\', \'[Ne] 3s2 3p6\', \'Used in welding and to protect reactive elements.\', \'https://image.jimcdn.com/app/cms/image/transf/dimension=304x1024:format=jpg/path/s21cd3466457ea560/image/i7802aebdc71832e0/version/1586086248/argon-gas-ampoule-excitable-argon-gas-ampoule-argon-gas-for-collection-rarefied-argon-gas-ampoule-how-to-light-up-argon-gas.jpg\')')
    cr.execute('insert into info values(\'Potassium\', 19, 39.098, \'s-block\', \'Alkali metal\', \'[Ar] 4s1\', \'They are used as a fertilizer in agriculture, horticulture, and hydroponic culture in the form of chloride (KCl), sulfate (K2SO4), or nitrate (KNO3), representing the \'\'K\'\' in NPK\',\'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Potassium-2.jpg/330px-Potassium-2.jpg\')')
    cr.execute('insert into info values(\'Calcium\', 20, 40.078, \'s-block\', \'Alkaline earth metal\', \'[Ar] 4s2\', \'The Ca2+ ion acts as an electrolyte and is vital to the health of the muscular, circulatory, and digestive systems; is indispensable to the building of bone in the form of hydroxyapatite; and supports synthesis and function of blood cells.\',\'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Calcium_unter_Argon_Schutzgasatmosph%C3%A4re.jpg/330px-Calcium_unter_Argon_Schutzgasatmosph%C3%A4re.jpg\')')
    cr.execute('insert into info values(\'Scandium\', 21, 44.956, \'d-block\', \'Transition metal\', \'[Ar] 4s2 3d1\', \'Used in aerospace alloys and sports equipment.\', \'https://www.neyco.fr/uploads/media/product/0001/07/scandium_1629288610.jpg\')')
    cr.execute('insert into info values(\'Titanium\', 22, 47.867, \'d-block\', \'Transition metal\', \'[Ar] 4s2 3d2\', \'Used in strong, lightweight alloys for aircraft and implants.\', \'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSohgdWy77LHZ4WKvYAgcpFCkhQs2jrHRTHg&s\')')
    cr.execute('insert into info values(\'Vanadium\', 23, 50.942, \'d-block\', \'Transition metal\', \'[Ar] 4s2 3d3\', \'Used in steel alloys to increase strength and corrosion resistance.\', \'https://cdn.britannica.com/76/8876-004-A60911FD/Vanadinite-Globe-Ariz.jpg\')')
    cr.execute('insert into info values(\'Chromium\', 24, 51.996, \'d-block\', \'Transition metal\', \'[Ar] 4s1 3d5\', \'Used in stainless steel and chrome plating.\', \'https://5.imimg.com/data5/MO/UO/TS/SELLER-86228968/chromium-metal-500x500.jpg\')')
    cr.execute('insert into info values(\'Manganese\', 25, 54.93, \'d-block\', \'Transition metal\', \'[Ar] 4s2 3d5\', \'Used in steel production and in aluminum alloys.\', \'https://images.prismic.io/xometry-marketing/e6de64d6-7ad8-495e-876e-15ca1cd34ba4_manganese.jpg?auto=compress%2Cformat&rect=166%2C0%2C667%2C667&w=486&h=486&fit=max\')')
    cr.execute('insert into info values(\'Iron\', 26, 55.845, \'d-block\', \'Transition metal\', \'[Ar] 4s2 3d6\', \'Essential for steel production and used in construction.\', \'https://media.istockphoto.com/id/172430480/photo/zinc-mine-nugget.jpg?s=612x612&w=0&k=20&c=ox-Fcv5jdeWY9wvagJMmcWLk5ohS_9dX5pTGgCo3pJ0=\')')
    cr.execute('insert into info values(\'Cobalt\', 27, 58.993, \'d-block\', \'Transition metal\', \'[Ar] 4s2 3d7\', \'Used in rechargeable batteries and superalloys.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmungAM8nVQmeSAEYniTPg8IKiunF6XW-4oQ&shttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmungAM8nVQmeSAEYniTPg8IKiunF6XW-4oQ&s\')')
    cr.execute('insert into info values(\'Nickel\', 28, 58.693, \'d-block\', \'Transition metal\', \'[Ar] 4s2 3d8\', \'Used in stainless steel and rechargeable batteries.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJQ0U0e_06ED5fwe8AHjXL_p8DYmYLDIZbUg&s\')')
    cr.execute('insert into info values(\'Copper\', 29, 63.546, \'d-block\', \'Transition metal\', \'[Ar] 4s1 3d10\', \'Widely used in electrical wiring and plumbing.\',\'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/NatCopper.jpg/640px-NatCopper.jpg\')')
    cr.execute('insert into info values(\'Zinc\', 30, 65.38, \'d-block\', \'Transition metal\', \'[Ar] 4s2 3d10\', \'Used for galvanizing steel and in batteries.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/07/Zinc-2.jpg\')')
    cr.execute('insert into info values(\'Gallium\', 31, 69.723, \'p-block\', \'Icosagen\', \'[Ar] 4s2 3d10 4p1\', \'Used in semiconductors and LED technology.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/07/Gallium-2.jpg\')')
    cr.execute('insert into info values(\'Germanium\', 32, 72.64, \'p-block\', \'Tetrels\', \'[Ar] 4s2 3d10 4p2\', \'Used in fiber optics and infrared optics.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/08/Germanium-2.jpg\')')
    cr.execute('insert into info values(\'Arsenic\', 33, 74.922, \'p-block\', \'Pnictogen\', \'[Ar] 4s2 3d10 4p3\', \'Used in semiconductors and wood preservatives.\',\'https://cdn1.byjus.com/wp-content/uploads/2016/04/Arsenic-2.jpg\')')
    cr.execute('insert into info values(\'Selenium\', 34, 78.96, \'p-block\', \'Chalcogen\', \'[Ar] 4s2 3d10 4p4\', \'Used in photocopiers and solar panels.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc_FPo8aorFtYQAhBQIaoppabBeesL4_0zcg&s\')')
    cr.execute('insert into info values(\'Bromine\', 35, 79.904, \'p-block\', \'Halogen\', \'[Ar] 4s2 3d10 4p5\', \'Used in flame retardants and water treatment.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/07/Bromine-2.jpg\')')
    cr.execute('insert into info values(\'Krypton\', 36, 83.798, \'p-block\', \'Noble gas\', \'[Ar] 4s2 3d10 4p6\', \'Used in lighting and photography flashes.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQITKrEpPcoDPCWbIIlRFi-esVsQBkrC_cX4P7PNkj-yxPporg1UqnvxOuH78dZjBtbx8c&usqp=CAU\')')
    cr.execute('insert into info values(\'Rubidium\', 37, 85.469, \'s-block\', \'Alkali metal\', \'[Kr] 5s1\', \' Rubidium has also been considered for use in a thermoelectric generator using the magnetohydrodynamic principle, whereby hot rubidium ions are passed through a magnetic field.\',\'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Rb5.JPG/330px-Rb5.JPG\')')
    cr.execute('insert into info values(\'Strontium\', 38, 87.62, \'s-block\', \'Alkaline earth metal\', \'[Kr] 5s2\', \'Sr is the active ingredient in Metastron, a radiopharmaceutical used for bone pain secondary to metastatic bone cancer\',\'https://www.chemicool.com/elements/images/300-strontium.jpg\')')
    cr.execute('insert into info values(\'Yttrium\', 39, 88.906, \'d-block\', \'Transition metal\', \'[Kr] 5s2 4d1\', \'Used in lasers and phosphors in TV screens.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaoLuaHEtZ_ABYreZxGqpoa05Awwe0JTPvUQ&s\')')
    cr.execute('insert into info values(\'Zirconium\', 40, 91.224, \'d-block\', \'Transition metal\', \'[Kr] 5s2 4d2\', \'Used in nuclear reactors and corrosion-resistant alloys.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/02/Zirconium-2.jpg\')')
    cr.execute('insert into info values(\'Niobium\', 41, 92.906, \'d-block\', \'Transition metal\', \'[Kr] 5s1 4d4\', \'Used in superconducting magnets and jet engines.\',\'https://cdn1.byjus.com/wp-content/uploads/2017/08/Niobium-2.jpg\')')
    cr.execute('insert into info values(\'Molybdenum\', 42, 95.95, \'d-block\', \'Transition metal\', \'[Kr] 5s1  4d5\', \'Used in steel alloys to increase hardness and resistance to corrosion.\',\'https://cdn1.byjus.com/wp-content/uploads/2016/08/Molybdenum-2.jpg\')')
    cr.execute('insert into info values(\'Technetium\', 43, 98, \'d-block\', \'Transition metal\', \'[Kr] 5s2 4d5\', \'Used in medical diagnostics and imaging.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/08/Technetium-2.jpg\')')
    cr.execute('insert into info values(\'Ruthenium\', 44, 101.07, \'d-block\', \'Transition metal\', \'[Kr] 5s1 4d7\', \'Used in electronics and as a catalyst in chemical reactions.\',\'https://i0.wp.com/periodic-table.com/wp-content/uploads/2018/12/Ruthenium.jpg?fit=225%2C225&ssl=1\')')
    cr.execute('insert into info values(\'Rhodium\', 45, 102.91, \'d-block\', \'Transition metal\', \'[Kr] 5s1 4d8\', \'Used in catalytic converters and jewelry.\',\'https://twelvesilvertrees.com/cdn/shop/articles/18193fcd36a65513259786877bee2df8.jpg?v=1697297240\')')
    cr.execute('insert into info values(\'Palladium\', 46, 106.42, \'d-block\', \'Transition metal\', \'[Kr] 4d10\', \'Used in catalytic converters and hydrogen storage.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/08/Palladium-2.jpg\')')
    cr.execute('insert into info values(\'Silver\', 47, 107.87, \'d-block\', \'Transition metal\', \'[Kr] 5s1 4d10\', \'Used in electronics, jewelry, and photography.\',\'https://i0.wp.com/geologyscience.com/wp-content/uploads/2019/06/Silver.png?fit=500%2C363&ssl=1\')')
    cr.execute('insert into info values(\'Cadmium\', 48, 112.41, \'d-block\', \'Transition metal\', \'[Kr] 5s2 4d10\', \'Used in batteries and pigments.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1vJEeA8VsVmzPu9QVeu9lkk4nm9bY2qDyMA&s\')')
    cr.execute('insert into info values(\'Indium\', 49, 114.82, \'p-block\', \'Icosagen\', \'[Kr] 5s2 4d10 5p1\', \'Used in touchscreens and semiconductors.\',\'https://cdn.mos.cms.futurecdn.net/EmE4MmqR4GzYfF3MhzotFm-320-80.jpg\')')
    cr.execute('insert into info values(\'Tin\', 50, 118.71, \'p-block\', \'Tetrels\', \'[Kr] 5s2 4d10 5p2\', \'Used in soldering and coating metals to prevent corrosion.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/08/Tin-2-1.jpg\')')
    cr.execute('insert into info values(\'Antimony\', 51, 121.76, \'p-block\', \'Pnictogen\', \'[Kr] 5s2 4d10 5p3\', \'Used in flame retardants and lead-acid batteries.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/08/Antimony-2.jpg\')')
    cr.execute('insert into info values(\'Tellurium\', 52, 127.6, \'p-block\', \'Chalcogen\', \'[Kr] 5s2 4d10 5p4\', \'Used in solar panels and thermoelectric devices.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdHDV-1EjFhoKfBzdTnFCK9iAcdtKz7L7RAA&s\')')
    cr.execute('insert into info values(\'Iodine\', 53, 126.9, \'p-block\', \'Halogen\', \'[Kr] 5s2 4d10 5p5\', \'Used as a disinfectant and in medical imaging.\', \'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Iodine_monochloride1.jpg/220px-Iodine_monochloride1.jpg\')')
    cr.execute('insert into info values(\'Xenon\', 54, 131.39, \'p-block\', \'Noble gas\', \'[Kr] 5s2 4d10 5p6\', \'Used in high-intensity lamps and medical imaging.\',\'https://i.namu.wiki/i/B7jSE3LMbk3YXqGEwgq8ntiXaqu29PDEjAb558nC6cQlJXXgNGhHNokqKxSNBH6HssNb5yk2PSQx-lk3BFKgIQ.webp\')')
    cr.execute('insert into info values(\'Caesium\', 55, 132.91, \'s-block\', \'Alkali metal\', \'[Xe] 6s1\', \'Caesium-based atomic clocks use the electromagnetic transitions in the hyperfine structure of caesium-133 atoms as a reference point\',\'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/CsCrystals.JPG/330px-CsCrystals.JPG\')')
    cr.execute('insert into info values(\'Barium\', 56, 137.33, \'s-block\', \'Alkaline earth metal\', \'[Xe] 6s2\', \'Used in medical imaging and fireworks.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/04/Barium-2-1.jpg\')')
    cr.execute('insert into info values(\'Lanthanum\', 57, 138.91, \'d-block\', \'Transition metal\', \'[Xe] 6s2 5d1\', \'Used in camera lenses and as a catalyst in oil refineries.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/01/Lanthanum-2.jpg\')')
    cr.execute('insert into info values(\'Cerium\', 58, 140.12, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 5d1 4f1\', \'Used in catalytic converters and glass polishing.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/01/Cerium-2.jpg\')')
    cr.execute('insert into info values(\'Praseodumium\', 59, 140.91, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f3\', \'Used in magnets and aircraft engines.\',\'https://cdn1.byjus.com/wp-content/uploads/2018/01/Praseodymium-2.jpg\')')
    cr.execute('insert into info values(\'Neodymium\', 60, 144.24, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f4\', \'Used in powerful magnets for electronics and wind turbines.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSchn6aPdm3EXgYzwtunOfnzufUP0MklT7SWg&s\')')
    cr.execute('insert into info values(\'Promethium\', 61, 145, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f5\', \'Used in nuclear batteries and luminous paint.\',\'https://www.newtondesk.com/wp-content/uploads/2018/07/Promethium-element-glow-in-the-dark.png\')')
    cr.execute('insert into info values(\'Samarium\', 62, 150.36, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f6\', \'Used in strong magnets and cancer treatment.\',\'https://periodictable.com/Samples/062.6/s9s.JPG\')')
    cr.execute('insert into info values(\'Europium\', 63, 151.96, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f7\', \'Used in phosphorescent and fluorescent applications.\', \'https://image.made-in-china.com/202f0j00mzfGAjqCLDck/Rare-Earth-Metals-Europium-Price-99-9-in-China.jpg\')')
    cr.execute('insert into info values(\'Gadolinum\', 64, 157.25, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 5d1 4f7\', \'Used in MRI contrast agents and nuclear reactors.\', \'https://auremo.net/1485-home_default/gadolinium-element-64-metal-rare-bell-metal-gd-pieces-9995.jpg\')')
    cr.execute('insert into info values(\'Terbium\', 65, 158.93, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f9\', \'Used in green phosphors for TV screens and LEDs.\', \'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Tb-sulfate-luminescence.jpg/200px-Tb-sulfate-luminescence.jpg\')')
    cr.execute('insert into info values(\'Dysprosium\', 66, 162.5, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f10\', \' Used in magnets and nuclear reactor control rods.\', \'https://i0.wp.com/periodic-table.com/wp-content/uploads/2018/12/Dysprosium.jpg?fit=225%2C225&ssl=1\')')
    cr.execute('insert into info values(\'Holmium\', 67, 164.93, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f11\', \'Used in lasers and nuclear control rods.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Holmium-2.jpg\')')
    cr.execute('insert into info values(\'Erbium\', 68, 167.26, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f12\', \'Used in fiber optic cables and lasers.\', \'https://chemicool.com/elements/images/300-erbium.jpg\')')
    cr.execute('insert into info values(\'Thulium\', 69, 168.93, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f13\', \'Used in portable X-ray devices and lasers.\', \'https://www.epi-materials.com/wp-content/uploads/2019/09/Thulium-1.jpg\')')
    cr.execute('insert into info values(\'Ytterbium\', 70, 173.04, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 4f14\', \'Used in atomic clocks and lasers.\', \'https://chemicool.com/elements/images/300-ytterbium-nucleus-shells.jpg\')')
    cr.execute('insert into info values(\'Lutetium\', 71, 174.97, \'f-block\', \'Lanthanides\', \'[Xe] 6s2 5d1 4f14\', \'Used in PET scans and as a catalyst in petroleum refining.\', \'https://sciencenotes.org/wp-content/uploads/2017/09/lutetium.jpg\')')
    cr.execute('insert into info values(\'Hafnium\', 72, 178.49, \'d-block\', \'Transition metal\', \'[Xe] 6s2 4f14 5d2\', \'Used in nuclear control rods and superalloys.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Hafnium-2.jpg\')')
    cr.execute('insert into info values(\'Tantalum\', 73, 180.95, \'d-block\', \'Transition metal\', \'[Xe] 6s2 4f14 5d3\', \'Used in capacitors and medical implants.\', \'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrxwlBJNjMORmJy9AFpuHHG9mftSSvT83mXA&s\')')
    cr.execute('insert into info values(\'Tungsten\', 74, 183.84, \'d-block\', \'Transition metal\', \'[Xe] 6s2 4f14 5d4\', \'Used in light bulb filaments and cutting tools.\', \'https://www.shutterstock.com/image-photo/single-glowing-round-bulb-tungsten-260nw-401236951.jpg\')')
    cr.execute('insert into info values(\'Rhenium\', 75, 186.21, \'d-block\', \'Transition metal\', \'[Xe] 6s2 4f14 5d5\', \'Used in jet engines and platinum-rhenium catalysts.\', \'https://images-of-elements.com/rhenium.jpg\')')
    cr.execute('insert into info values(\'Osmium\', 76, 190.23, \'d-block\', \'Transition metal\', \'[Xe] 6s2 4f14 5d6\', \'Used in fountain pen tips and electrical contacts\', \'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Osmium_cluster.jpg/220px-Osmium_cluster.jpg\')')
    cr.execute('insert into info values(\'Iridium\', 77, 192.22, \'d-block\', \'Transition metal\', \'[Xe] 6s2 4f14 5d7\', \'Used in spark plugs and crucibles for high-temperature materials.\', \'https://upload.wikimedia.org/wikipedia/commons/a/a8/Iridium-2.jpg\')')
    cr.execute('insert into info values(\'Platinum\', 78, 195.08, \'d-block\', \'Transition metal\', \'[Xe] 6s1 4f14 5d9\', \'Used in catalytic converters and jewelry.\', \'https://www.thenaturalsapphirecompany.com/education/wp-content/uploads/2017/12/platinum-nugget.jpg\')')
    cr.execute('insert into info values(\'Gold\', 79, 196.97, \'d-block\', \'Transition metal\', \'[Xe] 6s1 4f14 5d10\', \'Used in electronics, jewelry, and financial reserves.\', \'https://i.tribune.com.pk/media/images/IMG15452Blog_Paytm_Gold-Rates-Historical-Data-for-1725004329-0/IMG15452Blog_Paytm_Gold-Rates-Historical-Data-for-1725004329-0-436x333.webp\')')
    cr.execute('insert into info values(\'Mercury\', 80, 200.59, \'d-block\', \'Transition metal\', \'[Xe] 6s2 4f14 5d10\', \'Used in thermometers and fluorescent lighting.\', \'https://3.imimg.com/data3/UR/LJ/MY-3092514/mercury-liquid-500x500.jpg\')')
    cr.execute('insert into info values(\'Thallium\', 81, 204.38, \'p-block\', \'Icosagen\', \'[Xe] 6s2 4f14 5d10 6p1\', \'Used in electronics and medical imaging.\', \'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Thallium_pieces_in_ampoule.jpg/640px-Thallium_pieces_in_ampoule.jpg\')')
    cr.execute('insert into info values(\'Lead\', 82, 207.20, \'p-block\', \'Tetrels\', \'[Xe] 6s2 4f14 5d10 6p2\', \'Used in batteries and radiation shielding.\', \'https://cdn.britannica.com/00/154500-004-780E9EAF.jpg\')')
    cr.execute('insert into info values(\'Bismuth\', 83, 208.98, \'p-block\', \'Pnictogen\', \'[Xe] 6s2 4f14 5d10 p3\', \'Used in pharmaceuticals and fire detection devices.\', \'https://www.belmontmetals.com/wp-content/uploads/2017/09/bismuth-960-390-510x390.jpg\')')
    cr.execute('insert into info values(\'Polonium\', 84, 209, \'p-block\', \'Chalcogen\', \'[Xe] 6s2 4f14 5d10 6p4\', \'Used in antistatic devices and nuclear power sources\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Polonium-2.jpg\')')
    cr.execute('insert into info values(\'Astatine\', 85, 210, \'p-block\', \'Halogen\', \'[Xe] 6s2 4f14 5d10 6p5\', \'Used in cancer treatment and radiotherapy.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Astatine-2.jpg\')')
    cr.execute('insert into info values(\'Radon\', 86, 222, \'p-block\', \'Noble gas\', \'[Xe] 6s2 4f14 5d10 6p6\', \'Used in cancer treatment and geological research.\', \'https://periodictable.com/Samples/086.4/s9s.JPG\')')
    cr.execute('insert into info values(\'Francium\', 87, 223, \'s-block\', \'Alkali metal\', \'[Rn] 7s1\', \'Francium\'\'s ability to be synthesized, trapped, and cooled, along with its relatively simple atomic structure, has made it the subject of specialized spectroscopy experiments\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Francium-2.jpg\')')
    cr.execute('insert into info values(\'Radium\', 88, 226, \'s-block\', \'Alkaline earth metal\', \'[Rn] 7s2\', \'Used in luminous paints and cancer treatment.\', \'https://lh6.googleusercontent.com/proxy/Y3vwKT-IoyxiWZGtKH9wwjLR91_Lt4nfpiXB2C-5z-Ol2o5HpSTrBUEuJZR3dSGfJBZHY7xlNG7rRsTrc6hstAnxkeEFyxQW\')')
    cr.execute('insert into info values(\'Actinium\', 89, 227, \'d-block\', \'Transition metal\', \'[Rn] 7s2 6d1\', \'Used in radiation therapy and research.\', \'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN603am4NeDLwiZFhtLrWSaxdJFGOuvSMQPA&s\')')
    cr.execute('insert into info values(\'Thorium\', 90, 232.04, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 6d2\', \'Used in nuclear reactors and gas mantles.\', \'https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_article/public/cgov_image/media_image/800/800/files/thorium.jpg?h=4965b7f7&itok=2-Nn8PVg\')')
    cr.execute('insert into info values(\'Protactinium\', 91, 231.04, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 6d1 5f2\', \'Used in scientific research and nuclear reactors.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Protactinium-2.jpg\')')
    cr.execute('insert into info values(\'Uranium\', 92, 238.03, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 6d1 5f3\', \'Used as fuel in nuclear reactors and weapons.\', \'https://upload.wikimedia.org/wikipedia/commons/c/c1/Uranium_ore_square.jpg\')')
    cr.execute('insert into info values(\'Neptunium\', 93, 237.05, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 6d1 5f4\', \'Used in scientific research and potential nuclear reactors.\', \'https://upload.wikimedia.org/wikipedia/en/a/a3/1g_of_neptunium_metal.jpg\')')
    cr.execute('insert into info values(\'Plutonium\', 94, 244, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 5f6\', \'Used in nuclear weapons and power sources.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Plutonium-2.jpg\')')
    cr.execute('insert into info values(\'Americum\', 95, 243, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 5f7\', \'Used in smoke detectors and radiography.\', \'https://i0.wp.com/periodic-table.com/wp-content/uploads/2018/12/Americium.jpg?fit=225%2C224&ssl=1\')')
    cr.execute('insert into info values(\'Curium\', 96, 247, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 6d1 5f7\', \'Used in space exploration and cancer treatment.\', \'https://i0.wp.com/periodic-table.com/wp-content/uploads/2019/01/Curium.jpg?fit=225%2C225&ssl=1\')')
    cr.execute('insert into info values(\'Berkelium\', 97, 246, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 5f9\', \'Used in scientific research and isotope production.\', \'https://upload.wikimedia.org/wikipedia/commons/b/b6/Berkelium_metal.jpg\')')
    cr.execute('insert into info values(\'Californium\', 98, 251, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 5f10\', \'Used in nuclear reactors and cancer treatment.\', \'https://www.ccdc.cam.ac.uk/media/elements/Californium.jpg\')')
    cr.execute('insert into info values(\'Einsteinium\', 99, 252, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 5f11\', \'Used in scientific research and nuclear isotope production.\', \'https://upload.wikimedia.org/wikipedia/commons/5/55/Einsteinium.jpg\')')
    cr.execute('insert into info values(\'Fermium\', 100, 257, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 5f12\', \'Used in scientific research on heavy elements.\', \'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Fermium-Ytterbium_Alloy.jpg/220px-Fermium-Ytterbium_Alloy.jpg\')')
    cr.execute('insert into info values(\'Mendelevium\', 101, 258, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 5f13\', \'Used in scientific research on nuclear reactions.\', \'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXjCURKA4FtPw5dHXYsO1vJiBX4G-DhdyEUg&s\')')
    cr.execute('insert into info values(\'Nobelium\', 102, 259, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 5f14\', \'Used in scientific research on atomic structures.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Nobelium-2.jpg\')')
    cr.execute('insert into info values(\'Lawrencium\', 103, 262, \'f-block\', \'Lanthanides\', \'[Rn] 7s2 5f14 7p1\', \'Used in scientific research on atomic behavior.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Lawrencium-2.jpg\')')
    cr.execute('insert into info values(\'Rutherfordium\', 104, 267, \'d-block\', \'Transition metal\', \'[Rn] 7s2 5f14 6d2\', \'Used in scientific research on superheavy elements.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Rutherfordium-2.jpg\')')
    cr.execute('insert into info values(\'Dubnium\', 105, 262, \'d-block\', \'Transition metal\', \'[Rn] 7s2 5f14 6d3\', \'Used in scientific research on element properties.\', \'https://whatmaster.com/wp-content/uploads/2020/10/Einsteinium-L-min-6.jpg\')')
    cr.execute('insert into info values(\'Seaborgium\', 106, 269, \'d-block\', \'Transition metal\', \'[Rn] 7s2 5f14 6d4\', \'Used in scientific research on atomic nuclei.\', \'https://www.chemistrylearner.com/wp-content/uploads/2018/01/Seaborgium.jpg\')')
    cr.execute('insert into info values(\'Bohrium\', 107, 264, \'d-block\', \'Transition metal\', \'[Rn] 7s2 5f14 6d5\', \'Used in scientific research on nuclear physics.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Bohrium-2.jpg\')')
    cr.execute('insert into info values(\'Hassium\', 108, 269, \'d-block\', \'Transition metal\', \'[Rn] 7s2 5f14 6d6\', \'Used in scientific research on nuclear reactions.\', \'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Molybdenit_1.jpg/220px-Molybdenit_1.jpg\')')
    cr.execute('insert into info values(\'Meitnerium\', 109, 278, \'d-block\', \'Transition metal\', \'[Rn] 7s2 5f14 6d7\', \'Used in scientific research on nuclear structures.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Meitnerium-2.jpg\')')
    cr.execute('insert into info values(\'Damstadtium\', 110, 281, \'d-block\', \'Transition metal\', \'[Rn] 7s2 5f14 6d8\', \'Used in scientific research on heavy elements.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Darmstadtium-2.jpg\')')
    cr.execute('insert into info values(\'Roentgenium\', 111, 282, \'d-block\', \'Transition metal\', \'[Rn] 7s2 5f14 6d9\', \'Used in scientific research on atomic behavior.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Roentgenium-2.jpg\')')
    cr.execute('insert into info values(\'Copernicium\', 112, 285, \'d-block\', \'Transition metal\', \'[Rn] 7s2 5f14 6d10\', \'Used in scientific research on superheavy elements.\', \'https://chauhan-copernicium.weebly.com/uploads/3/8/9/2/38924751/6522234.jpg?250\')')
    cr.execute('insert into info values(\'Nihonium\', 113, 286, \'p-block\', \'Icosagen\', \'[Rn] 7s2 5f14 6d10 7p1\', \'Used in scientific research on new elements.\', \'https://study.com/cimages/multimages/16/360px-nihonium_shells.svg8971291457619994040.png\')')
    cr.execute('insert into info values(\'Flerovium\', 114, 289, \'p-block\', \'Tetrels\', \'[Rn]  7s2 5f14 6d10 7p2\', \'Used in scientific research on atomic physics.\', \'https://cdn1.byjus.com/wp-content/uploads/2018/08/Flerovium-2.jpg\')')
    cr.execute('insert into info values(\'Moscovium\', 115, 289, \'p-block\', \'Pnictogen\', \'[Rn] 7s2 5f14 6d10 7p3\', \'Used in scientific research on element stability.\', \'https://media.sciencephoto.com/image/c0131858/400wm\')')
    cr.execute('insert into info values(\'Livermorium\', 116, 293, \'p-block\', \'Chalcogen\', \'[Rn] 7s2 5f14 6d10 7p4\', \'A highly radioactive metal, of which only a few atoms have ever been made. At present, it is only used in research. It has no known biological role.\',\'https://www.americanelements.com/images_graphics/element-bohr-models/livermorium-bohr-model.jpg\')')
    cr.execute('insert into info values(\'Tennessine\', 117, 294, \'p-block\', \'Halogen\', \'[Rn] 7s2 5f14 6d10 7p5\', \'Its only use at all is as a subject for research. It may provide insights into the nature of heavy atoms, atomic stability, or aid in nuclear research.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQz9ap4frqSkgNfs3iPNblS5uK2tXzv46VOA&s\')')
    cr.execute('insert into info values(\'Oganesson\', 118, 294, \'p-block\', \'Noble gas\', \'[Rn] 7s2 5f14 6d10 7p6\', \'At present, it is only used in research.\',\'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtY_OqF3u47hahjsUca8WK-3P6PgRianrMxg&s\')')
    d.commit()
else:
    cr.execute('use periodic_table')


window = tk.Tk()
window.title("Periodic Table")
window.geometry("1545x650")
window.configure(bg="lightcyan")


text_frame = tk.Frame(window, bg="lightcyan")
text_frame.place(x=400, y=5, height=300, width=400)  

text_box = tk.Text(text_frame, height=300, width=40)
text_box.config(font=('Comic Sans MS', 10))
text_box.pack(side=tk.TOP, fill=tk.BOTH, expand=True)

frame = tk.Frame(master=window, padx=10)
frame.config(bg="lightcyan")
frame.pack(side=tk.TOP, expand=True, padx=10, pady=10)

image_frame = tk.Frame(window, bg="lightcyan")
image_frame.place(x=1000, y=5, height=180, width=400)

def element_info(atm_no):
    global image_label
    cr.execute(f'SELECT * FROM info WHERE atm_no = {atm_no}')
    result = cr.fetchone()
    if result:
        info = f"{result[0]}\nAtomic Number: {result[1]}\nAtomic Mass: {result[2]}\nBlock: {result[3]}\nGroup: {result[4]}\nConfiguration: {result[5]}\nApplication: {result[6]}"
        image_url = result[7] 
        
        if image_url:
            try:
                response = requests.get(image_url)
                response.raise_for_status()
                image_data = response.content
                img = Image.open(io.BytesIO(image_data))
                text_box_width = text_box.winfo_width()
                text_box_height = text_box.winfo_height()

                img_resized = img.resize((text_box_width, text_box_height), Image.LANCZOS)
                photo = ImageTk.PhotoImage(img_resized)
                
                if 'image_label' in globals():
                    image_label.destroy()  
                
                image_label = tk.Label(image_frame, image=photo)
                image_label.image = photo  
                image_label.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True)  
            except requests.exceptions.RequestException as e:
                print(f"Error fetching image: {e}")
    else:
        info = "No information available"
    
    display_info(info)  

def clear_textbox():
    text_box.delete(1.0, 'end')
    image_label.destroy()

b =tk.Button(window, text='Clear',bg="orange",width=10,height=1,command=clear_textbox)
b.pack()

h = tk.Button(window, text='Facts', bg="orange",width=10,height=1, command = facts)
h.pack()

nlabel= tk.Label(window, text="By Nitya Gargi Srivastava\n25BCE10147\nVIT Bhopal",bg='lightcyan')
nlabel.place(x=1300, y=600)

g1 = tk.Label(frame, text="Group 1", font=("Arial", 10), bg="lightcyan")
g1.grid(row =2, column=2)
g2 = tk.Label(frame, text="Group 2", font=("Arial", 10), bg="lightcyan")
g2.grid(row =2, column=3)
g3 = tk.Label(frame, text="Group 3", font=("Arial", 10), bg="lightcyan")
g3.grid(row =2, column=4)
g4 = tk.Label(frame, text="Group 4", font=("Arial", 10), bg="lightcyan")
g4.grid(row =2, column=5)
g5 = tk.Label(frame, text="Group 5", font=("Arial", 10), bg="lightcyan")
g5.grid(row =2, column=6)
g6 = tk.Label(frame, text="Group 6", font=("Arial", 10), bg="lightcyan")
g6.grid(row =2, column=7)
g7 = tk.Label(frame, text="Group 7", font=("Arial", 10), bg="lightcyan")
g7.grid(row =2, column=8)
g8 = tk.Label(frame, text="Group 8", font=("Arial", 10), bg="lightcyan")
g8.grid(row =2, column=9)
g9 = tk.Label(frame, text="Group 9", font=("Arial", 10), bg="lightcyan")
g9.grid(row =2, column=10)
g10 = tk.Label(frame, text="Group 10", font=("Arial", 10), bg="lightcyan")
g10.grid(row =2, column=11)
g11= tk.Label(frame, text="Group 11", font=("Arial", 10), bg="lightcyan")
g11.grid(row =2, column=12)
g12 = tk.Label(frame, text="Group 12", font=("Arial", 10), bg="lightcyan")
g12.grid(row =2, column=13)
g13 = tk.Label(frame, text="Group 13", font=("Arial", 10), bg="lightcyan")
g13.grid(row =2, column=14)
g14 = tk.Label(frame, text="Group 14", font=("Arial", 10), bg="lightcyan")
g14.grid(row =2, column=15)
g15 = tk.Label(frame, text="Group 15", font=("Arial", 10), bg="lightcyan")
g15.grid(row =2, column=16)
g16 = tk.Label(frame, text="Group 16", font=("Arial", 10), bg="lightcyan")
g16.grid(row =2, column=17)
g17 = tk.Label(frame, text="Group 17", font=("Arial", 10), bg="lightcyan")
g17.grid(row =2, column=18)
g18 = tk.Label(frame, text="Group 18", font=("Arial", 10), bg="lightcyan")
g18.grid(row =2, column=19)

b1 = tk.Label(frame, text="1", font=("Arial", 10), bg="lightcyan")
b1.grid(row=3, column=1)
b2 = tk.Label(frame, text="2", font=("Arial", 10), bg="lightcyan")
b2.grid(row=4, column=1)
b3 = tk.Label(frame, text="3", font=("Arial", 10), bg="lightcyan")
b3.grid(row=5, column=1)
b4 = tk.Label(frame, text="4", font=("Arial", 10), bg="lightcyan")
b4.grid(row=6, column=1)
b5 = tk.Label(frame, text="5", font=("Arial", 10), bg="lightcyan")
b5.grid(row=7, column=1)
b6 = tk.Label(frame, text="6", font=("Arial", 10), bg="lightcyan")
b6.grid(row=8, column=1)
b7 = tk.Label(frame, text="7", font=("Arial", 10), bg="lightcyan")
b7.grid(row=9, column=1)

button_1 = tk.Button(master=frame, text='H',bg="plum", padx=3,pady=5, width=10, command = lambda :element_info(1))
button_1.grid(row=3, column=2, pady=2)
button_2 = tk.Button(master=frame, text='He',bg="skyblue", padx=3,pady=5, width=10, command = lambda : element_info(2))
button_2.grid(row=3, column=19, pady=2)
button_3 = tk.Button(master=frame, text='Li',bg="lightsalmon",padx=3,pady=5, width=10, command = lambda : element_info(3))
button_3.grid(row=4, column=2, pady=2)
button_4 = tk.Button(master=frame, text='Be',bg="mistyrose",padx=3,pady=5, width=10, command = lambda : element_info(4))
button_4.grid(row=4, column=3, pady=2)
button_5 = tk.Button(master=frame, text='B',bg="lightgreen",padx=3,pady=5, width=10, command = lambda : element_info(5))
button_5.grid(row=4, column=14, pady=2)
button_6 = tk.Button(master=frame, text='C',bg="yellow",padx=3,pady=5, width=10, command = lambda : element_info(6))
button_6.grid(row=4, column=15, pady=2)
button_7 = tk.Button(master=frame, text='N',bg="coral",padx=3,pady=5, width=10, command = lambda : element_info(7))
button_7.grid(row=4, column=16, pady=2)
button_8 = tk.Button(master=frame, text='O',bg="beige",padx=3,pady=5, width=10, command = lambda : element_info(8))
button_8.grid(row=4, column=17, pady=2)
button_9 = tk.Button(master=frame, text='F',bg="aqua",padx=3,pady=5, width=10, command = lambda : element_info(9))
button_9.grid(row=4, column=18, pady=2)
button_10 = tk.Button(master=frame, text='Ne',bg="skyblue",padx=3,pady=5, width=10, command = lambda : element_info(10))
button_10.grid(row=4, column=19, pady=2)
button_11 = tk.Button(master=frame, text='Na',bg="lightsalmon",padx=3,pady=5, width=10, command = lambda : element_info(11))
button_11.grid(row=5, column=2, pady=2)
button_12 = tk.Button(master=frame, text='Mg',bg="mistyrose",padx=3,pady=5, width=10, command = lambda : element_info(12))
button_12.grid(row=5, column=3, pady=2)
button_13 = tk.Button(master=frame, text='Al',bg="lightgreen",padx=3,pady=5, width=10, command = lambda : element_info(13))
button_13.grid(row=5, column=14, pady=2)
button_14 = tk.Button(master=frame, text='Si',bg="yellow",padx=3,pady=5, width=10, command = lambda : element_info(14))
button_14.grid(row=5, column=15, pady=2)
button_15 = tk.Button(master=frame, text='P',bg="coral",padx=3,pady=5, width=10, command = lambda : element_info(15))
button_15.grid(row=5, column=16, pady=2)
button_16 = tk.Button(master=frame, text='S',bg="beige",padx=3,pady=5, width=10, command = lambda : element_info(16))
button_16.grid(row=5, column=17, pady=2)
button_17 = tk.Button(master=frame, text='Cl',bg="cyan",padx=3,pady=5, width=10, command = lambda : element_info(17))
button_17.grid(row=5, column=18, pady=2)
button_18 = tk.Button(master=frame, text='Ar',bg="skyblue",padx=3,pady=5, width=10, command = lambda : element_info(18))
button_18.grid(row=5, column=19, pady=2)
button_19 = tk.Button(master=frame, text='K',bg="lightsalmon",padx=3,pady=5, width=10, command = lambda : element_info(19))
button_19.grid(row=6, column=2, pady=2)
button_20 = tk.Button(master=frame, text='Ca',bg="mistyrose",padx=3,pady=5, width=10, command = lambda : element_info(20))
button_20.grid(row=6, column=3, pady=2)
button_21 = tk.Button(master=frame, text='Sc',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(21))
button_21.grid(row=6, column=4, pady=2)
button_22 = tk.Button(master=frame, text='Ti',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(22))
button_22.grid(row=6, column=5, pady=2)
button_23 = tk.Button(master=frame, text='V',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(23))
button_23.grid(row=6, column=6, pady=2)
button_24 = tk.Button(master=frame, text='Cr',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(24))
button_24.grid(row=6, column=7, pady=2)
button_25 = tk.Button(master=frame, text='Mn',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(25))
button_25.grid(row=6, column=8, pady=2)
button_26 = tk.Button(master=frame, text='Fe',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(26))
button_26.grid(row=6, column=9, pady=2)
button_27 = tk.Button(master=frame, text='Co',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(27))
button_27.grid(row=6, column=10, pady=2)
button_28 = tk.Button(master=frame, text='Ni',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(28))
button_28.grid(row=6, column=11, pady=2)
button_29 = tk.Button(master=frame, text='Cu',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(29))
button_29.grid(row=6, column=12, pady=2)
button_30 = tk.Button(master=frame, text='Zn',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(30))
button_30.grid(row=6, column=13, pady=2)
button_31 = tk.Button(master=frame, text='Ga',bg="lightgreen",padx=3,pady=5, width=10, command = lambda : element_info(31))
button_31.grid(row=6, column=14, pady=2)
button_32 = tk.Button(master=frame, text='Ge',bg="yellow",padx=3,pady=5, width=10, command = lambda : element_info(32))
button_32.grid(row=6, column=15, pady=2)
button_33 = tk.Button(master=frame, text='As',bg="coral",padx=3,pady=5, width=10, command = lambda : element_info(33))
button_33.grid(row=6, column=16, pady=2)
button_34= tk.Button(master=frame, text='Se',bg="beige",padx=3,pady=5, width=10, command = lambda : element_info(34))
button_34.grid(row=6, column=17, pady=2)
button_35 = tk.Button(master=frame, text='Br',bg="cyan",padx=3,pady=5, width=10, command = lambda : element_info(35))
button_35.grid(row=6, column=18, pady=2)
button_36 = tk.Button(master=frame, text='Kr',bg="skyblue",padx=3,pady=5, width=10, command = lambda : element_info(36))
button_36.grid(row=6, column=19, pady=2)
button_37 = tk.Button(master=frame, text='Rb',bg="lightsalmon",padx=3,pady=5, width=10, command = lambda : element_info(37))
button_37.grid(row=7, column=2, pady=2)
button_38 = tk.Button(master=frame, text='Sr',bg="mistyrose",padx=3,pady=5, width=10, command = lambda : element_info(38))
button_38.grid(row=7, column=3, pady=2)
button_39 = tk.Button(master=frame, text='Y',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(39))
button_39.grid(row=7, column=4, pady=2)
button_40 = tk.Button(master=frame, text='Zr',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(40))
button_40.grid(row=7, column=5, pady=2)
button_41 = tk.Button(master=frame, text='Nb',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(41))
button_41.grid(row=7, column=6, pady=2)
button_42 = tk.Button(master=frame, text='Mo',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(42))
button_42.grid(row=7, column=7, pady=2)
button_43 = tk.Button(master=frame, text='Tc',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(43))
button_43.grid(row=7, column=8, pady=2)
button_44 = tk.Button(master=frame, text='Ru',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(44))
button_44.grid(row=7, column=9, pady=2)
button_45 = tk.Button(master=frame, text='Rh',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(45))
button_45.grid(row=7, column=10, pady=2)
button_46 = tk.Button(master=frame, text='Pd',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(46))
button_46.grid(row=7, column=11, pady=2)
button_47 = tk.Button(master=frame, text='Ag',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(47))
button_47.grid(row=7, column=12, pady=2)
button_48 = tk.Button(master=frame, text='Cd',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(48))
button_48.grid(row=7, column=13, pady=2)
button_49 = tk.Button(master=frame, text='In',bg="lightgreen",padx=3,pady=5, width=10, command = lambda : element_info(49))
button_49.grid(row=7, column=14, pady=2)
button_50 = tk.Button(master=frame, text='Sn',bg="yellow",padx=3,pady=5, width=10, command = lambda : element_info(50))
button_50.grid(row=7, column=15, pady=2)
button_51 = tk.Button(master=frame, text='Sb',bg="coral",padx=3,pady=5, width=10, command = lambda : element_info(51))
button_51.grid(row=7, column=16, pady=2)
button_52 = tk.Button(master=frame, text='Te',bg="beige",padx=3,pady=5, width=10, command = lambda : element_info(52))
button_52.grid(row=7, column=17, pady=2)
button_53 = tk.Button(master=frame, text='I',bg="cyan",padx=3,pady=5, width=10, command = lambda : element_info(53))
button_53.grid(row=7, column=18, pady=2)
button_54 = tk.Button(master=frame, text='Xe',bg="skyblue",padx=3,pady=5, width=10, command = lambda : element_info(54))
button_54.grid(row=7, column=19, pady=2)
button_55 = tk.Button(master=frame, text='Cs',bg="lightsalmon",padx=3,pady=5, width=10, command = lambda : element_info(55))
button_55.grid(row=8, column=2, pady=2)
button_56 = tk.Button(master=frame, text='Ba',bg="mistyrose",padx=3,pady=5, width=10, command = lambda : element_info(56))
button_56.grid(row=8, column=3, pady=2)
button_57 = tk.Button(master=frame, text='La*',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(57))
button_57.grid(row=8, column=4, pady=2)
button_58 = tk.Button(master=frame, text='*Ce',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(58))
button_58.grid(row=11, column=4, pady=2)
button_59 = tk.Button(master=frame, text='Pr',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(59))
button_59.grid(row=11, column=5, pady=2)
button_60 = tk.Button(master=frame, text='Nd',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(60))
button_60.grid(row=11, column=6, pady=2)
button_61 = tk.Button(master=frame, text='Pm',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(61))
button_61.grid(row=11, column=7, pady=2)
button_62 = tk.Button(master=frame, text='Sm',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(62))
button_62.grid(row=11, column=8, pady=2)
button_63 = tk.Button(master=frame, text='Eu',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(63))
button_63.grid(row=11, column=9, pady=2)
button_64 = tk.Button(master=frame, text='Gd',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(64))
button_64.grid(row=11, column=10, pady=2)
button_65 = tk.Button(master=frame, text='Tb',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(65))
button_65.grid(row=11, column=11, pady=2)
button_66 = tk.Button(master=frame, text='Dy',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(66))
button_66.grid(row=11, column=12, pady=2)
button_67 = tk.Button(master=frame, text='Ho',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(67))
button_67.grid(row=11, column=13, pady=2)
button_68 = tk.Button(master=frame, text='Er',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(68))
button_68.grid(row=11, column=14, pady=2)
button_69 = tk.Button(master=frame, text='Tm',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(69))
button_69.grid(row=11, column=15, pady=2)
button_70 = tk.Button(master=frame, text='Yb',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(70))
button_70.grid(row=11, column=16, pady=2)
button_71 = tk.Button(master=frame, text='Lu',bg="khaki",padx=3,pady=5, width=10, command = lambda : element_info(71))
button_71.grid(row=11, column=17, pady=2)
button_72 = tk.Button(master=frame, text='Hf',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(72))
button_72.grid(row=8, column=5, pady=2)
button_73 = tk.Button(master=frame, text='Ta',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(73))
button_73.grid(row=8, column=6, pady=2)
button_74 = tk.Button(master=frame, text='W',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(74))
button_74.grid(row=8, column=7, pady=2)
button_75 = tk.Button(master=frame, text='Re',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(75))
button_75.grid(row=8, column=8, pady=2)
button_76 = tk.Button(master=frame, text='Os',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(76))
button_76.grid(row=8, column=9, pady=2)
button_77 = tk.Button(master=frame, text='Ir',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(77))
button_77.grid(row=8, column=10, pady=2)
button_78 = tk.Button(master=frame, text='Pt',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(78))
button_78.grid(row=8, column=11, pady=2)
button_79 = tk.Button(master=frame, text='Au',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(79))
button_79.grid(row=8, column=12, pady=2)
button_80 = tk.Button(master=frame, text='Hg',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(80))
button_80.grid(row=8, column=13, pady=2)
button_81 = tk.Button(master=frame, text='Tl',bg="lightgreen",padx=3,pady=5, width=10, command = lambda : element_info(81))
button_81.grid(row=8, column=14, pady=2)
button_82 = tk.Button(master=frame, text='Pb',bg="yellow",padx=3,pady=5, width=10, command = lambda : element_info(82))
button_82.grid(row=8, column=15, pady=2)
button_83 = tk.Button(master=frame, text='Bi',bg="coral",padx=3,pady=5, width=10, command = lambda : element_info(83))
button_83.grid(row=8, column=16, pady=2)
button_84 = tk.Button(master=frame, text='Po',bg="beige",padx=3,pady=5, width=10, command = lambda : element_info(84))
button_84.grid(row=8, column=17, pady=2)
button_85 = tk.Button(master=frame, text='At',bg="cyan",padx=3,pady=5, width=10, command = lambda : element_info(85))
button_85.grid(row=8, column=18, pady=2)
button_86 = tk.Button(master=frame, text='Rn',bg="skyblue",padx=3,pady=5, width=10, command = lambda : element_info(86))
button_86.grid(row=8, column=19, pady=2)
button_87 = tk.Button(master=frame, text='Fr',bg="lightsalmon",padx=3,pady=5, width=10, command = lambda : element_info(87))
button_87.grid(row=9, column=2, pady=2)
button_88 = tk.Button(master=frame, text='Ra',bg="mistyrose",padx=3,pady=5, width=10, command = lambda : element_info(88))
button_88.grid(row=9, column=3, pady=2)
button_89 = tk.Button(master=frame, text='Ac**',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(89))
button_89.grid(row=9, column=4, pady=2)
button_90 = tk.Button(master=frame, text='**Th',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(90))
button_90.grid(row=12, column=4, pady=2)
button_91 = tk.Button(master=frame, text='Pa',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(91))
button_91.grid(row=12, column=5, pady=2)
button_92 = tk.Button(master=frame, text='U',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(92))
button_92.grid(row=12, column=6, pady=2)
button_93 = tk.Button(master=frame, text='Np',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(93))
button_93.grid(row=12, column=7, pady=2)
button_94 = tk.Button(master=frame, text='Pu',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(94))
button_94.grid(row=12, column=8, pady=2)
button_95 = tk.Button(master=frame, text='Am',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(95))
button_95.grid(row=12, column=9, pady=2)
button_96 = tk.Button(master=frame, text='Cm',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(96))
button_96.grid(row=12, column=10, pady=2)
button_97 = tk.Button(master=frame, text='Bk',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(97))
button_97.grid(row=12, column=11, pady=2)
button_98 = tk.Button(master=frame, text='Cf',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(98))
button_98.grid(row=12, column=12, pady=2)
button_99 = tk.Button(master=frame, text='Es',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(99))
button_99.grid(row=12, column=13, pady=2)
button_100 = tk.Button(master=frame, text='Fm',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(100))
button_100.grid(row=12, column=14, pady=2)
button_101 = tk.Button(master=frame, text='Md',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(101))
button_101.grid(row=12, column=15, pady=2)
button_102 = tk.Button(master=frame, text='No',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(102))
button_102.grid(row=12, column=16, pady=2)
button_103 = tk.Button(master=frame, text='Lr',bg="deeppink",padx=3,pady=5, width=10, command = lambda : element_info(103))
button_103.grid(row=12, column=17, pady=2)
button_104 = tk.Button(master=frame, text='Rf',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(104))
button_104.grid(row=9, column=5, pady=2)
button_105 = tk.Button(master=frame, text='Db',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(105))
button_105.grid(row=9, column=6, pady=2)
button_106 = tk.Button(master=frame, text='Sg',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(106))
button_106.grid(row=9, column=7, pady=2)
button_107 = tk.Button(master=frame, text='Bh',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(107))
button_107.grid(row=9, column=8, pady=2)
button_108 = tk.Button(master=frame, text='Hs',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(108))
button_108.grid(row=9, column=9, pady=2)
button_109 = tk.Button(master=frame, text='Mt',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(109))
button_109.grid(row=9, column=10, pady=2)
button_110 = tk.Button(master=frame, text='Ds',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(110))
button_110.grid(row=9, column=11, pady=2)
button_111 = tk.Button(master=frame, text='Rg',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(111))
button_111.grid(row=9, column=12, pady=2)
button_112 = tk.Button(master=frame, text='Cn',bg="aquamarine",padx=3,pady=5, width=10, command = lambda : element_info(112))
button_112.grid(row=9, column=13, pady=2)
button_113 = tk.Button(master=frame, text='Nh',bg="lightgreen",padx=3,pady=5, width=10, command = lambda : element_info(113))
button_113.grid(row=9, column=14, pady=2)
button_114 = tk.Button(master=frame, text='Fl',bg="yellow",padx=3,pady=5, width=10, command = lambda : element_info(114))
button_114.grid(row=9, column=15, pady=2)
button_115 = tk.Button(master=frame, text='Mc',bg="coral",padx=3,pady=5, width=10, command = lambda : element_info(115))
button_115.grid(row=9, column=16, pady=2)
button_116 = tk.Button(master=frame, text='Lv',bg="beige",padx=3,pady=5, width=10, command = lambda : element_info(116))
button_116.grid(row=9, column=17, pady=2)
button_117 = tk.Button(master=frame, text='Ts',bg="cyan",padx=3,pady=5, width=10, command = lambda : element_info(117))
button_117.grid(row=9, column=18, pady=2)
button_118 = tk.Button(master=frame, text='Og',bg="skyblue",padx=3,pady=5, width=10, command = lambda : element_info(118))
button_118.grid(row=9, column=19, pady=2)



window.mainloop()

cr.close()
d.close()
